/*
 * This file is part of Cleanflight and Betaflight.
 *
 * Cleanflight and Betaflight are free software. You can redistribute
 * this software and/or modify this software under the terms of the
 * GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * Cleanflight and Betaflight are distributed in the hope that they
 * will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this software.
 *
 * If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * Axiovel fork: axio-nav state link, STATE frame v1 serializer tests.
 *
 * The golden frame bytes are generated by the independent, spec-derived
 * Python implementation (axio-nav M2 scratch: state_link_golden.py), so
 * this test cross-checks the firmware serializer against the protocol
 * spec (docs/state-link-protocol.md), not against itself.
 */

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

extern "C" {
    #include "platform.h"

    #include "common/axis.h"
    #include "common/crc.h"
    #include "common/maths.h"
    #include "common/vector.h"

    #include "drivers/motor.h"
    #include "drivers/serial.h"

    #include "fc/runtime_config.h"

    #include "flight/imu.h"
    #include "flight/mixer.h"

    #include "io/serial.h"

    #include "rx/rx.h"

    #include "sensors/acceleration.h"
    #include "sensors/battery.h"
    #include "sensors/gyro.h"
    #include "sensors/sensors.h"

    #include "telemetry/state_link.h"

    // firmware globals the unit under test reads
    gyro_t gyro;
    acc_t acc;
    float motor[MAX_SUPPORTED_MOTORS];
    uint8_t armingFlags = 0;

    // test-controlled stub state
    uint16_t testBatteryVoltage = 0;     // 10 mV units
    int32_t testAmperage = 0;            // centiamps
    bool testFailsafeActive = false;
    bool testGyroCalibrationComplete = true;
    bool testAccCalibrationComplete = true;
    uint32_t testSensorsMask = 0;
    quaternion_t testQuaternion = QUATERNION_INITIALIZE;
    uint8_t testMotorCount = 4;
}

#include "unittest_macros.h"
#include "gtest/gtest.h"

// Golden STATE v1 frame, generated by state_link_golden.py from:
//   timestamp_us = 0x12345678
//   gyro         = ( 1.0, -2.5, 3.14159265 )   [rad/s, FRD]
//   accel        = ( 0.5, -9.80665, 1.25 )     [m/s^2, FRD]
//   quat         = ( 0.92387953, 0.0, -0.38268343, 0.125 )
//   motor        = ( 0, 1024, 2047, 123 )
//   vbat_mv      = 8400
//   current_ca   = 1234
//   flags        = 0x05 (ARMED | CALIBRATING)
//   seq          = 0xAB
static const uint8_t goldenFrame[STATE_LINK_STATE_FRAME_SIZE] = {
    0xA5, 0x01, 0x01, 0x3A, 0x78, 0x56, 0x34, 0x12, 0x00, 0x00, 0x80, 0x3F,
    0x00, 0x00, 0x20, 0xC0, 0xDB, 0x0F, 0x49, 0x40, 0x00, 0x00, 0x00, 0x3F,
    0x0A, 0xE8, 0x1C, 0xC1, 0x00, 0x00, 0xA0, 0x3F, 0x5E, 0x83, 0x6C, 0x3F,
    0x00, 0x00, 0x00, 0x00, 0x15, 0xEF, 0xC3, 0xBE, 0x00, 0x00, 0x00, 0x3E,
    0x00, 0x00, 0x00, 0x04, 0xFF, 0x07, 0x7B, 0x00, 0xD0, 0x20, 0xD2, 0x04,
    0x05, 0xAB, 0x9C,
};

TEST(StateLinkTest, GoldenFrameByteExact)
{
    stateLinkStateFrame_t frame;
    frame.timestampUs = 0x12345678;
    frame.gyroRadS[0] = 1.0f;
    frame.gyroRadS[1] = -2.5f;
    frame.gyroRadS[2] = 3.14159265f;
    frame.accelMps2[0] = 0.5f;
    frame.accelMps2[1] = -9.80665f;
    frame.accelMps2[2] = 1.25f;
    frame.quat[0] = 0.92387953f;
    frame.quat[1] = 0.0f;
    frame.quat[2] = -0.38268343f;
    frame.quat[3] = 0.125f;
    frame.motor[0] = 0;
    frame.motor[1] = 1024;
    frame.motor[2] = 2047;
    frame.motor[3] = 123;
    frame.vbatMv = 8400;
    frame.currentCa = 1234;
    frame.flags = STATE_LINK_FLAG_ARMED | STATE_LINK_FLAG_CALIBRATING;
    frame.seq = 0xAB;

    uint8_t buf[STATE_LINK_STATE_FRAME_SIZE];
    memset(buf, 0x55, sizeof(buf));
    const int length = stateLinkSerializeStateFrame(buf, &frame);

    EXPECT_EQ(STATE_LINK_STATE_FRAME_SIZE, length);
    for (int i = 0; i < STATE_LINK_STATE_FRAME_SIZE; i++) {
        EXPECT_EQ(goldenFrame[i], buf[i]) << "frame byte " << i;
    }
}

TEST(StateLinkTest, CrcSpanExcludesSyncByte)
{
    // a corrupted sync byte must not change the CRC; a corrupted version must
    stateLinkStateFrame_t frame;
    memset(&frame, 0, sizeof(frame));
    uint8_t buf[STATE_LINK_STATE_FRAME_SIZE];
    stateLinkSerializeStateFrame(buf, &frame);

    const uint8_t crc = buf[STATE_LINK_STATE_FRAME_SIZE - 1];
    EXPECT_EQ(crc, crc8_dvb_s2_update(0, &buf[1], STATE_LINK_STATE_FRAME_SIZE - 2));
    EXPECT_NE(crc, crc8_dvb_s2_update(0, &buf[0], STATE_LINK_STATE_FRAME_SIZE - 2));
}

TEST(StateLinkTest, SampleStateMapsBetaflightToWireConventions)
{
    // Betaflight body FLU -> wire body FRD: negate y/z of gyro and accel
    gyro.gyroADCf[X] = 10.0f;   // deg/s
    gyro.gyroADCf[Y] = 20.0f;
    gyro.gyroADCf[Z] = 30.0f;

    acc.dev.acc_1G_rec = 1.0f / 512;
    acc.accADC.x = 512.0f;      // +1 g
    acc.accADC.y = 256.0f;      // +0.5 g
    acc.accADC.z = -1024.0f;    // -2 g

    // Quaternion mapping is build-dependent (see state_link.c):
    //   - SITL FDM-injected attitude is already FRD->NED -> pass-through
    //   - hardware Mahony attitude is FLU->NWU -> negate y/z components
    testQuaternion.w = 0.4f;
    testQuaternion.x = 0.5f;
    testQuaternion.y = 0.6f;
    testQuaternion.z = -0.7f;

    // motorConvertToExternal() is stubbed as identity (values already
    // "external" 1000..2000)
    testMotorCount = 4;
    motor[0] = 1000.0f;
    motor[1] = 1500.0f;
    motor[2] = 2000.0f;
    motor[3] = 1250.0f;

    testBatteryVoltage = 840;   // 8.40 V
    testAmperage = 1234;        // 12.34 A

    armingFlags = 0;
    ENABLE_ARMING_FLAG(ARMED);
    testFailsafeActive = false;
    testGyroCalibrationComplete = false;  // -> CALIBRATING
    testAccCalibrationComplete = true;
    testSensorsMask = SENSOR_ACC;

    stateLinkStateFrame_t frame;
    stateLinkSampleState(&frame, (timeUs_t)0xDEADBEEF);

    EXPECT_EQ(0xDEADBEEFu, frame.timestampUs);

    EXPECT_NEAR(10.0f * M_PIf / 180, frame.gyroRadS[0], 1e-6f);
    EXPECT_NEAR(-20.0f * M_PIf / 180, frame.gyroRadS[1], 1e-6f);
    EXPECT_NEAR(-30.0f * M_PIf / 180, frame.gyroRadS[2], 1e-6f);

#if defined(SIMULATOR_BUILD) && !defined(USE_IMU_CALC) && !defined(SET_IMU_FROM_EULER)
    // SITL: accADC carries FDM-injected KINEMATIC acceleration, all-axis
    // negated (see state_link.c); the transmitter reconstructs specific
    // force f_b = -accADC*scale - R^T(q)(0,0,g) with the wire attitude.
    // Independently computed (python) for accADC=(512,256,-1024) at
    // acc_1G=512 and q=(0.4,0.5,0.6,-0.7) (norm^2=1.26):
    //   a_FRD = (-9.80665, -4.903325, 19.6133)
    //   g_b   = (-9.184006, -3.424544, 0.311322)
    EXPECT_NEAR(-0.622644f, frame.accelMps2[0], 1e-4f);
    EXPECT_NEAR(-1.478781f, frame.accelMps2[1], 1e-4f);
    EXPECT_NEAR(19.301978f, frame.accelMps2[2], 1e-4f);
#else
    // Hardware: accADC is true specific force, FLU -> FRD (negate y/z).
    EXPECT_NEAR(9.80665f, frame.accelMps2[0], 1e-4f);
    EXPECT_NEAR(-4.903325f, frame.accelMps2[1], 1e-4f);
    EXPECT_NEAR(19.6133f, frame.accelMps2[2], 1e-4f);
#endif

#if defined(SIMULATOR_BUILD) && !defined(USE_IMU_CALC) && !defined(SET_IMU_FROM_EULER)
    // SITL: internal quaternion already FRD->NED, transmitted unchanged.
    // The previous unconditional negation double-converted here, putting
    // nose-down-positive pitch (and mirrored yaw) on the wire -- the
    // axio-nav PR-8 wobble-diagnosis side finding.
    EXPECT_FLOAT_EQ(0.4f, frame.quat[0]);
    EXPECT_FLOAT_EQ(0.5f, frame.quat[1]);
    EXPECT_FLOAT_EQ(0.6f, frame.quat[2]);
    EXPECT_FLOAT_EQ(-0.7f, frame.quat[3]);
#else
    // Hardware: FLU->NWU -> FRD->NED via the Rx(pi) similarity (negate y/z).
    EXPECT_FLOAT_EQ(0.4f, frame.quat[0]);
    EXPECT_FLOAT_EQ(0.5f, frame.quat[1]);
    EXPECT_FLOAT_EQ(-0.6f, frame.quat[2]);
    EXPECT_FLOAT_EQ(0.7f, frame.quat[3]);
#endif

    EXPECT_EQ(0, frame.motor[0]);
    EXPECT_EQ(1024, frame.motor[1]);
    EXPECT_EQ(2047, frame.motor[2]);
    EXPECT_EQ(512, frame.motor[3]);

    EXPECT_EQ(8400, frame.vbatMv);
    EXPECT_EQ(1234, frame.currentCa);

    EXPECT_EQ(STATE_LINK_FLAG_ARMED | STATE_LINK_FLAG_CALIBRATING, frame.flags);
}

#if defined(SIMULATOR_BUILD) && !defined(USE_IMU_CALC) && !defined(SET_IMU_FROM_EULER)
// SITL specific-force reconstruction (state_link.c SIMULATOR_BUILD accel
// branch): the wire must carry spec specific force -- a resting level
// vehicle reads (0, 0, -g), NOT the FDM's kinematic zero. Canonical
// attitudes, golden values per the spec definition.
TEST(StateLinkTest, SampleStateSitlAccelIsSpecificForce)
{
    constexpr float kG = 9.80665f;

    memset(&gyro, 0, sizeof(gyro));
    memset(&acc, 0, sizeof(acc));
    acc.dev.acc_1G_rec = 1.0f / 512;
    testMotorCount = 0;
    testBatteryVoltage = 0;
    testAmperage = 0;
    armingFlags = 0;
    testFailsafeActive = false;
    testGyroCalibrationComplete = true;
    testAccCalibrationComplete = true;
    testSensorsMask = 0;

    stateLinkStateFrame_t frame;

    // Resting, level (kinematic accel = 0 -> accADC = 0; q = identity):
    // the pre-fix transmitter put exactly 0 on the wire here -- the
    // signature non-conformance of the axio-nav estimator-v1 finding.
    testQuaternion.w = 1.0f;
    testQuaternion.x = 0.0f;
    testQuaternion.y = 0.0f;
    testQuaternion.z = 0.0f;
    stateLinkSampleState(&frame, 0);
    EXPECT_NEAR(0.0f, frame.accelMps2[0], 1e-5f);
    EXPECT_NEAR(0.0f, frame.accelMps2[1], 1e-5f);
    EXPECT_NEAR(-kG, frame.accelMps2[2], 1e-4f);

    // Resting, inverted (roll pi): specific force points out the roof.
    testQuaternion.w = 0.0f;
    testQuaternion.x = 1.0f;
    stateLinkSampleState(&frame, 0);
    EXPECT_NEAR(0.0f, frame.accelMps2[0], 1e-4f);
    EXPECT_NEAR(0.0f, frame.accelMps2[1], 1e-4f);
    EXPECT_NEAR(kG, frame.accelMps2[2], 1e-4f);

    // Resting, nose up 90 deg (pitch +pi/2): specific force along +x.
    testQuaternion.w = 0.70710678f;
    testQuaternion.x = 0.0f;
    testQuaternion.y = 0.70710678f;
    stateLinkSampleState(&frame, 0);
    EXPECT_NEAR(kG, frame.accelMps2[0], 1e-4f);
    EXPECT_NEAR(0.0f, frame.accelMps2[1], 1e-4f);
    EXPECT_NEAR(0.0f, frame.accelMps2[2], 1e-4f);

    // Dynamic, level: the injection-path x flip must be undone.
    // accADC = (512, 256, -1024) at acc_1G = 512 was injected as
    // a_FRD = -(accADC)/512*g = (-g, -g/2, 2g); f = a - (0,0,g).
    testQuaternion.w = 1.0f;
    testQuaternion.x = 0.0f;
    testQuaternion.y = 0.0f;
    acc.accADC.x = 512.0f;
    acc.accADC.y = 256.0f;
    acc.accADC.z = -1024.0f;
    stateLinkSampleState(&frame, 0);
    EXPECT_NEAR(-9.80665f, frame.accelMps2[0], 1e-4f);
    EXPECT_NEAR(-4.903325f, frame.accelMps2[1], 1e-4f);
    EXPECT_NEAR(9.80665f, frame.accelMps2[2], 1e-4f);
}
#endif

TEST(StateLinkTest, SampleStateClampsAndFlags)
{
    memset(&gyro, 0, sizeof(gyro));
    memset(&acc, 0, sizeof(acc));
    acc.dev.acc_1G_rec = 1.0f / 2048;

    testMotorCount = 2;             // motors 3/4 not populated -> 0
    motor[0] = 2500.0f;             // out of range -> clamps to full scale
    motor[1] = 500.0f;              // out of range -> clamps to 0
    motor[2] = 2000.0f;
    motor[3] = 2000.0f;

    testBatteryVoltage = 7000;      // 70.00 V -> 70000 mV, clamps to 65535
    testAmperage = -50;             // negative -> clamps to 0

    armingFlags = 0;
    testFailsafeActive = true;
    testGyroCalibrationComplete = true;
    testAccCalibrationComplete = false;
    testSensorsMask = SENSOR_ACC;   // acc present and uncalibrated -> CALIBRATING

    stateLinkStateFrame_t frame;
    stateLinkSampleState(&frame, 0);

    EXPECT_EQ(2047, frame.motor[0]);
    EXPECT_EQ(0, frame.motor[1]);
    EXPECT_EQ(0, frame.motor[2]);
    EXPECT_EQ(0, frame.motor[3]);

    EXPECT_EQ(65535, frame.vbatMv);
    EXPECT_EQ(0, frame.currentCa);

    EXPECT_EQ(STATE_LINK_FLAG_FAILSAFE | STATE_LINK_FLAG_CALIBRATING, frame.flags);

    // acc absent -> not calibrating
    testSensorsMask = 0;
    stateLinkSampleState(&frame, 0);
    EXPECT_EQ(STATE_LINK_FLAG_FAILSAFE, frame.flags);
}

// STUBS

extern "C" {

uint16_t getBatteryVoltage(void)
{
    return testBatteryVoltage;
}

int32_t getAmperage(void)
{
    return testAmperage;
}

bool failsafeIsActive(void)
{
    return testFailsafeActive;
}

bool gyroIsCalibrationComplete(void)
{
    return testGyroCalibrationComplete;
}

bool accIsCalibrationComplete(void)
{
    return testAccCalibrationComplete;
}

bool sensors(uint32_t mask)
{
    return (testSensorsMask & mask) != 0;
}

void getQuaternion(quaternion_t *quat)
{
    *quat = testQuaternion;
}

uint16_t motorConvertToExternal(float motorValue)
{
    return (uint16_t)motorValue;
}

uint8_t getMotorCount(void)
{
    return testMotorCount;
}

const uint32_t baudRates[] = {0, 9600, 19200, 38400, 57600, 115200, 230400,
                              250000, 400000, 460800, 500000, 921600, 1000000,
                              1500000, 2000000, 2470000};

const serialPortConfig_t *findSerialPortConfig(serialPortFunction_e function)
{
    UNUSED(function);
    return NULL;
}

serialPort_t *openSerialPort(serialPortIdentifier_e identifier,
                             serialPortFunction_e function,
                             serialReceiveCallbackPtr rxCallback,
                             void *rxCallbackData,
                             uint32_t baudRate,
                             portMode_e mode,
                             portOptions_e options)
{
    UNUSED(identifier);
    UNUSED(function);
    UNUSED(rxCallback);
    UNUSED(rxCallbackData);
    UNUSED(baudRate);
    UNUSED(mode);
    UNUSED(options);
    return NULL;
}

uint32_t serialTxBytesFree(const serialPort_t *instance)
{
    UNUSED(instance);
    return 0;
}

void serialWriteBuf(serialPort_t *instance, const uint8_t *data, int count)
{
    UNUSED(instance);
    UNUSED(data);
    UNUSED(count);
}

// referenced by stateLinkProcess()'s SIMULATOR_BUILD branch
void serialWrite(serialPort_t *instance, uint8_t ch)
{
    UNUSED(instance);
    UNUSED(ch);
}

}
